In [12]:
import pandas as pd
import numpy as np
from pathlib import Path

DATA = Path("../data")
print("Files in data/:", [f.name for f in DATA.iterdir()])

Files in data/: ['bodmas_malware_category.csv', 'bodmas.npz', 'features_poc.jsonl', 'bodmas_metadata.csv', 'test_pe']

In [13]:
meta = pd.read_csv(DATA / "bodmas_metadata.csv")
print("shape:", meta.shape)
print("columns:", list(meta.columns))
meta.head()

shape: (134435, 3)
columns: ['sha', 'timestamp', 'family']

,sha,timestamp,family
0,e6d7b4bab32def853ab564410df53fa33172dda1bfd48c...,2007-01-01 08:46:39+00:00,NaN
1,5af37a058a5bcf2284c183ee98d92b7c66d8f5ce623e92...,2007-01-26 17:16:30+00:00,NaN
2,5bfbbea150af5cef2d3a93b80ef7c7faea9f564b56045d...,2007-03-21 02:08:53+00:00,NaN
3,216f592f1e1717d5681b7f5f2b14a28a2f0c603b5b7318...,2007-04-25 12:55:06+00:00,NaN
4,a1ca76813d2e9e7e23b830c87fbe29bcb51fcbe096e445...,2007-11-14 15:03:55+00:00,NaN

In [14]:
# How many benign vs malware (malware = has a family label)
print("Total rows:", len(meta))
print("Benign (no family):", meta["family"].isna().sum())
print("Malware (has family):", meta["family"].notna().sum())
print("Number of distinct families:", meta["family"].nunique())

Total rows: 134435
Benign (no family): 77142
Malware (has family): 57293
Number of distinct families: 582

In [15]:
cat = pd.read_csv(DATA / "bodmas_malware_category.csv")
print("shape:", cat.shape)
print("columns:", list(cat.columns))
cat.head(10)

shape: (57293, 2)
columns: ['sha256', 'category']

                                              sha256    category
0  6a695877f571d043fe08d3cc715d9d4b4af85ffe837fa0...        worm
1  9ef9439795cac85e711b59df296a19e7ac43c144035f2f...      trojan
2  32de655f9010d8d152db16c6e5bbad215fa09286a08ff1...        worm
3  a68f7fb26ad84859625002395cf67f22ea0956996ed9c8...  downloader
4  d5c74472adfda20166a65f8b2886819a014ebcb67b999e...      trojan
5  c9c7384b5cd0bf22f6366caeb52af5e8f3d1265cbbb9d1...        worm
6  774b0ff235a2f50d983ca6b1fd6878a98bd3659954b63e...      trojan
7  b9198895114cea953666dc9380e55366759f9b769f1b3a...        worm
8  02450f54a5513dac224337207c8d6380d28e7e90f51c6d...        worm
9  7d8ea61dc1a7a6f84087d49a5bf0503925b07fbd8c2252...        worm

In [16]:
print("Distinct categories:", cat["category"].nunique())
print()
print(cat["category"].value_counts())

Distinct categories: 14

category
trojan                29972
worm                  16697
backdoor               7331
downloader             1031
ransomware              821
dropper                 715
informationstealer      448
virus                   192
pua                      29
cryptominer              20
p2p-worm                 16
exploit                  12
trojan-gamethief          6
rootkit                   3
Name: count, dtype: int64

In [17]:
import lief

pe = lief.parse("../data/test_pe/putty.exe")

print("=== Parsed:", pe.name if hasattr(pe, "name") else "putty.exe", "===")
print("\n--- Sections (name, size, entropy) ---")
for s in pe.sections:
    print(f"{s.name:10s}  size={s.size:>8}  entropy={s.entropy:.2f}")

=== Parsed: putty.exe ===

--- Sections (name, size, entropy) ---
.text       size=  970752  entropy=6.45
.rdata      size=  281600  entropy=5.41
.data       size=    4096  entropy=2.08
.pdata      size=   29184  entropy=5.91
.00cfg      size=     512  entropy=2.71
.gxfg       size=   11264  entropy=5.25
.tls        size=     512  entropy=-0.00
_RDATA      size=     512  entropy=4.13
.rsrc       size=  374272  entropy=7.83
.reloc      size=    8704  entropy=5.44

In [18]:
print("--- Imported libraries and a few functions each ---")
if pe.has_imports:
    for lib in pe.imports:
        funcs = [e.name for e in lib.entries if e.name]
        print(f"\n{lib.name}  ({len(funcs)} functions)")
        print("   ", ", ".join(funcs[:8]), "..." if len(funcs) > 8 else "")
else:
    print("No imports found")

--- Imported libraries and a few functions each ---

GDI32.dll  (51 functions)
    BitBlt, CreateBitmap, CreateCompatibleBitmap, CreateCompatibleDC, CreateFontA, CreateFontIndirectA, CreatePalette, CreatePen ...

IMM32.dll  (5 functions)
    ImmGetCompositionStringW, ImmGetContext, ImmReleaseContext, ImmSetCompositionFontA, ImmSetCompositionWindow

ole32.dll  (3 functions)
    CoCreateInstance, CoInitialize, CoUninitialize

USER32.dll  (119 functions)
    AppendMenuA, BeginPaint, CheckDlgButton, CheckMenuItem, CheckRadioButton, CloseClipboard, CreateCaret, CreateDialogParamA ...

KERNEL32.dll  (148 functions)
    Beep, ClearCommBreak, CloseHandle, CompareStringW, ConnectNamedPipe, CreateEventA, CreateFileA, CreateFileMappingA ...

SHELL32.dll  (1 functions)
    ShellExecuteA

COMDLG32.dll  (6 functions)
    ChooseColorA, ChooseFontA, GetOpenFileNameA, GetOpenFileNameW, GetSaveFileNameA, GetSaveFileNameW

ADVAPI32.dll  (15 functions)
    AllocateAndInitializeSid, CopySid, EqualSid, GetLengthSid, GetUserNameA, InitializeSecurityDescriptor, RegCloseKey, RegCreateKeyExA ...

In [19]:
data = np.load(DATA / "bodmas.npz")
X = data["X"]
y = data["y"]

print("X shape:", X.shape, " y shape:", y.shape)
print("X dtype:", X.dtype)
print("first 10 values of row 0:", X[0, :10])

X shape: (134435, 2381)  y shape: (134435,)
X dtype: float32
first 10 values of row 0: [0.05674198 0.00801749 0.00776239 0.00546647 0.00776239 0.00444606
 0.00543003 0.00306122 0.00947522 0.00630466]

In [20]:
import pandas as pd
from pathlib import Path

DATA = Path("../data")

# load the category labels (sha256 -> category)
cat = pd.read_csv(DATA / "bodmas_malware_category.csv")

# the 8 categories we care about
KEEP = ["trojan", "worm", "backdoor", "downloader",
        "ransomware", "informationstealer", "dropper", "virus"]

# pick a few samples from each category so the PoC spans classes
picks = []
for c in KEEP:
    rows = cat[cat["category"] == c].head(3)   # first 3 of each
    picks.append(rows)

sample = pd.concat(picks).reset_index(drop=True)
print("total picked:", len(sample))
print(sample["category"].value_counts())
sample

total picked: 24
category
trojan                3
worm                  3
backdoor              3
downloader            3
ransomware            3
informationstealer    3
dropper               3
virus                 3
Name: count, dtype: int64

                                               sha256            category
0   9ef9439795cac85e711b59df296a19e7ac43c144035f2f...              trojan
1   d5c74472adfda20166a65f8b2886819a014ebcb67b999e...              trojan
2   774b0ff235a2f50d983ca6b1fd6878a98bd3659954b63e...              trojan
3   6a695877f571d043fe08d3cc715d9d4b4af85ffe837fa0...                worm
4   32de655f9010d8d152db16c6e5bbad215fa09286a08ff1...                worm
5   c9c7384b5cd0bf22f6366caeb52af5e8f3d1265cbbb9d1...                worm
6   b04a8f775aae9cc1eeb35deb125432fffd385c1f71d317...            backdoor
7   148200ba66e55055a1a1423e44bde143e7d7a550122f7e...            backdoor
8   c5b03ce62adbf84fb26bd00e5826fabdc13224d01f965d...            backdoor
9   a68f7fb26ad84859625002395cf67f22ea0956996ed9c8...          downloader
10  bc51c382e750185f230aa557f48c82f2fcce3dd9532891...          downloader
11  95630aa97920265b9e5a29eaa91d392d5e0a6d5af68af2...          downloader
12  2fe80200d30a9839c675ea804886390624d3935283e6b8...          ransomware
13  c44a1c75e28b6d4911d92c5daef2df2b15ec7c6988f60f...          ransomware
14  13f35ef23b6c9aa653347b4fcfb5fc59fbef901dc5eace...          ransomware
15  b74775bb44f4e07680efeb061f4ab5c88cd91e17b90db5...  informationstealer
16  16a0e621fe72144448862ab550e3e94d565c5016aff677...  informationstealer
17  17e703d0d0ff76b93b8db25ba0846a3fad076381747a17...  informationstealer
18  fd8bc3762101023aaf6c56e45090bf91ab7d5ccc0ccc0b...             dropper
19  b0b92376470c090e712df259c222dcdb43bd6f07dbb404...             dropper
20  399d4220c047f842e362d38b0a8e5f8c111b79f548e093...             dropper
21  55705e9a092ec3d5c89fee270ff1003ba43fbb3553f68e...               virus
22  0a19f43b9afac2da5685988dd4a494096ac271b7a80384...               virus
23  fb50293b759f0d7bfc28202bd1b2e76de43a4789791706...               virus

In [21]:
import zipfile

ZIP_PATH = "/Volumes/Bodmas/BODMAS_disarmed_malware_binaries.zip"
OUT_DIR = Path("/Volumes/Bodmas/binaries")

with zipfile.ZipFile(ZIP_PATH) as z:
    for sha in sample["sha256"]:
        member = f"altered/{sha}.exe"          # its name inside the zip
        target = OUT_DIR / f"{sha}.exe"         # where it lands on the SSD
        with z.open(member) as src, open(target, "wb") as dst:
            dst.write(src.read())

print("extracted", len(sample), "files")
print("on disk:", len(list(OUT_DIR.glob("*.exe"))), "exe files")

extracted 24 files
on disk: 24 exe files

In [22]:
import sys
sys.path.append("../src")          # so we can import from the src folder
from extract import extract_features

# grab the first extracted binary
BIN_DIR = Path("/Volumes/Bodmas/binaries")
first = sorted(BIN_DIR.glob("*.exe"))[0]
print("testing on:", first.name)

result = extract_features(str(first))

if result is None:
    print("FAILED: LIEF returned None — the disarmed header broke parsing")
else:
    print("SUCCESS")
    print("num_sections:", result["num_sections"])
    print("section_names:", result["section_names"])
    print("num DLLs imported:", len(result["imports"]))

testing on: 0a19f43b9afac2da5685988dd4a494096ac271b7a8038481de3fc8c09a16da8d.exe
SUCCESS
num_sections: 9
section_names: ['CODE', 'DATA', 'BSS', '.idata', '.tls', '.rdata', '.reloc', '.rsrc', '.aspack']
num DLLs imported: 10

Failed to parse COFF string table
Failed to parse COFF symbol #0

In [23]:
label_map = dict(zip(cat["sha256"], cat["category"]))

rows = []
skipped = []

for path in sorted(BIN_DIR.glob("*.exe")):
    sha = path.stem
    record = extract_features(str(path))

    if record is None:
        skipped.append(sha)
        continue

    record["sha256"] = sha
    record["category"] = label_map[sha]
    rows.append(record)

features_df = pd.DataFrame(rows)

print("extracted:", len(features_df), "  skipped:", len(skipped))
print(features_df["category"].value_counts())
features_df.head()

extracted: 24   skipped: 0
category
virus                 3
ransomware            3
backdoor              3
informationstealer    3
worm                  3
dropper               3
trojan                3
downloader            3
Name: count, dtype: int64

Failed to parse COFF string table
Failed to parse COFF symbol #0
Failed to parse COFF string table
Failed to parse COFF symbol #0
Address of new exe header is corrupted
Failed to parse DOS Stub
Address of new exe header is corrupted
Failed to parse DOS Stub
Address of new exe header is corrupted
Failed to parse DOS Stub
Address of new exe header is corrupted
Failed to parse DOS Stub

,path,num_sections,section_names,section_entropies,imports,sha256,category
0,/Volumes/Bodmas/binaries/0a19f43b9afac2da56859...,9,"[CODE, DATA, BSS, .idata, .tls, .rdata, .reloc...","{'CODE': 6.52, 'DATA': 2.8, 'BSS': -0.0, '.ida...","{'kernel32.dll': ['Sleep'], 'user32.dll': ['Cr...",0a19f43b9afac2da5685988dd4a494096ac271b7a80384...,virus
1,/Volumes/Bodmas/binaries/13f35ef23b6c9aa653347...,6,"[.text, .rdata, .data, .gfids, .rsrc, .reloc]","{'.text': 6.67, '.rdata': 5.57, '.data': 3.07,...","{'KERNEL32.dll': ['GetConsoleOutputCP', 'Devic...",13f35ef23b6c9aa653347b4fcfb5fc59fbef901dc5eace...,ransomware
2,/Volumes/Bodmas/binaries/148200ba66e55055a1a14...,8,"[CODE, DATA, BSS, .idata, .tls, .rdata, .reloc...","{'CODE': 6.58, 'DATA': 4.78, 'BSS': 0.0, '.ida...",{'kernel32.dll': ['WritePrivateProfileStringA'...,148200ba66e55055a1a1423e44bde143e7d7a550122f7e...,backdoor
3,/Volumes/Bodmas/binaries/16a0e621fe72144448862...,9,"[CODE, DATA, BSS, .idata, .tls, .rdata, .reloc...","{'CODE': 6.4, 'DATA': 5.44, 'BSS': 0.0, '.idat...","{'kernel32.dll': ['GetProcAddress', 'GetModule...",16a0e621fe72144448862ab550e3e94d565c5016aff677...,informationstealer
4,/Volumes/Bodmas/binaries/17e703d0d0ff76b93b8db...,3,"[.text, .rsrc, .reloc]","{'.text': 7.68, '.rsrc': 4.36, '.reloc': 1.95}",{'mscoree.dll': ['_CorExeMain']},17e703d0d0ff76b93b8db25ba0846a3fad076381747a17...,informationstealer

In [24]:
OUT = Path("../data/features_poc.jsonl")
features_df.to_json(OUT, orient="records", lines=True)
print("saved", len(features_df), "rows to", OUT)

check = pd.read_json(OUT, lines=True)
print("read back:", len(check), "rows")
print("columns:", list(check.columns))

saved 24 rows to ../data/features_poc.jsonl
read back: 24 rows
columns: ['path', 'num_sections', 'section_names', 'section_entropies', 'imports', 'sha256', 'category']

In [25]:
features_df[["sha256", "category", "num_sections", "section_names", "imports"]].head(5)

,sha256,category,num_sections,section_names,imports
0,0a19f43b9afac2da5685988dd4a494096ac271b7a80384...,virus,9,"[CODE, DATA, BSS, .idata, .tls, .rdata, .reloc...","{'kernel32.dll': ['Sleep'], 'user32.dll': ['Cr..."
1,13f35ef23b6c9aa653347b4fcfb5fc59fbef901dc5eace...,ransomware,6,"[.text, .rdata, .data, .gfids, .rsrc, .reloc]","{'KERNEL32.dll': ['GetConsoleOutputCP', 'Devic..."
2,148200ba66e55055a1a1423e44bde143e7d7a550122f7e...,backdoor,8,"[CODE, DATA, BSS, .idata, .tls, .rdata, .reloc...",{'kernel32.dll': ['WritePrivateProfileStringA'...
3,16a0e621fe72144448862ab550e3e94d565c5016aff677...,informationstealer,9,"[CODE, DATA, BSS, .idata, .tls, .rdata, .reloc...","{'kernel32.dll': ['GetProcAddress', 'GetModule..."
4,17e703d0d0ff76b93b8db25ba0846a3fad076381747a17...,informationstealer,3,"[.text, .rsrc, .reloc]",{'mscoree.dll': ['_CorExeMain']}

In [26]:
import sys
sys.path.append("../src")
from enrich import enrich_one

sample_row = features_df.iloc[0].to_dict()

print("CATEGORY (for your reference only):", sample_row["category"])
print("SHA:", sample_row["sha256"][:16])
print()
print("FEATURES GIVEN TO MODEL:")
print("  sections:", sample_row["section_names"])
print("  imports:", list(sample_row["imports"].keys()))
print()
print("=" * 60)
print("MISTRAL DESCRIPTION:")
print("=" * 60)
description = enrich_one(sample_row)
print(description)

CATEGORY (for your reference only): virus
SHA: 0a19f43b9afac2da

FEATURES GIVEN TO MODEL:
  sections: ['CODE', 'DATA', 'BSS', '.idata', '.tls', '.rdata', '.reloc', '.rsrc', '.aspack']
  imports: ['kernel32.dll', 'user32.dll', 'advapi32.dll', 'oleaut32.dll', 'version.dll', 'gdi32.dll', 'ole32.dll', 'comctl32.dll', 'shell32.dll', 'ADVAPI32.DLL']

============================================================
MISTRAL DESCRIPTION:
============================================================
The program appears to be a graphical user interface (GUI) application with window management capabilities, potentially using custom images or icons. It can interact with system parameters, windows, menus, cursors, and clipboard data. It may also handle dialog boxes, pop-ups, scrollbars, and system messages. The program can manipulate the system's color palette, fonts, and brushes, suggesting graphical rendering capabilities. Network activity is not evident from the provided features. Persistence mechanisms or process/memory manipulation are not suggested by the given data. Evasion or packing techniques are also not indicated.

In [27]:
import pandas as pd
from pathlib import Path

features_df = pd.read_json("../data/features_poc.jsonl", lines=True)
print("loaded", len(features_df), "rows")

loaded 24 rows

In [28]:
import sys
sys.path.append("../src")
from enrich import enrich_one_cached

descriptions = []
for i, row in features_df.iterrows():
    record = row.to_dict()
    try:
        desc = enrich_one_cached(record)
    except Exception as e:
        desc = f"ERROR: {e}"
    descriptions.append(desc)
    print(f"[{i+1}/24] {row['category']:20s} done")

features_df["description"] = descriptions
print("\nall done -", len(descriptions), "descriptions generated")

[1/24] virus                done
[2/24] ransomware           done
[3/24] backdoor             done
[4/24] informationstealer   done
[5/24] informationstealer   done
[6/24] ransomware           done
[7/24] worm                 done
[8/24] dropper              done
[9/24] virus                done
[10/24] worm                 done
[11/24] trojan               done
[12/24] downloader           done
[13/24] trojan               done
[14/24] downloader           done
[15/24] backdoor             done
[16/24] dropper              done
[17/24] informationstealer   done
[18/24] downloader           done
[19/24] ransomware           done
[20/24] backdoor             done
[21/24] worm                 done
[22/24] trojan               done
[23/24] virus                done
[24/24] dropper              done

all done - 24 descriptions generated

In [30]:
for i, row in features_df.iterrows():
    print("=" * 70)
    print(f"[{i+1}] TRUE CATEGORY: {row['category']}")
    print(f"    imports: {list(row['imports'].keys())}")
    print(f"    sections: {row['section_names']}")
    print("-" * 70)
    print(row["description"])
    print()

======================================================================
[1] TRUE CATEGORY: virus
    imports: ['kernel32.dll', 'user32.dll', 'advapi32.dll', 'oleaut32.dll', 'version.dll', 'gdi32.dll', 'ole32.dll', 'comctl32.dll', 'shell32.dll', 'ADVAPI32.DLL']
    sections: ['CODE', 'DATA', 'BSS', '.idata', '.tls', '.rdata', '.reloc', '.rsrc', '.aspack']
----------------------------------------------------------------------
The program appears to be a graphical user interface (GUI) application with window management capabilities, potentially using custom images for its UI. It can interact with system parameters, create, manipulate, and destroy windows, menus, and cursors. It may also handle dialog boxes, scrollbars, and pop-ups. The program can communicate with the keyboard and mouse, manage the clipboard, and possibly respond to user input. Network activity is not evident from the provided features. Persistence mechanisms or process/memory manipulation are not suggested by the given data. Evasion or packing techniques are also not indicated.

======================================================================
[2] TRUE CATEGORY: ransomware
    imports: ['KERNEL32.dll', 'USER32.dll']
    sections: ['.text', '.rdata', '.data', '.gfids', '.rsrc', '.reloc']
----------------------------------------------------------------------
The program appears to be capable of process manipulation, file I/O operations, and some degree of interaction with the user interface. It utilizes functions for creating, allocating, and managing memory (VirtualAlloc, HeapSize, HeapAlloc, HeapReAlloc, HeapFree), handling files (CreateFileW, WriteFile, FindFirstFileExA, FindNextFileA), interacting with the console (GetConsoleOutputCP, WriteConsoleW), and manipulating processes (TerminateProcess, GetCurrentProcess). Additionally, it can access system information (GetSystemTimeAdjustment, GetLocaleInfoW, GetStringTypeW, GetCPInfo) and create events (CreateEventW). The program may also have some level of network activity through the use of CreateMailslotW, but this is not definitive. The entropy values suggest a mix of executable code and data sections, with no clear indicators of packing or evasion techniques.

======================================================================
[3] TRUE CATEGORY: backdoor
    imports: ['kernel32.dll', 'user32.dll', 'advapi32.dll', 'oleaut32.dll', 'wsock32.dll']
    sections: ['CODE', 'DATA', 'BSS', '.idata', '.tls', '.rdata', '.reloc', '.rsrc']
----------------------------------------------------------------------
The program appears to be capable of file operations (CreateFileA, CopyFileA, DeleteFileA, CreateDirectoryA), process manipulation (CreateThread, ExitProcess), registry access (RegQueryValueExA, RegOpenKeyExA, RegCloseKey), network activity (WSASocket, send, recv, gethostbyname), and resource management (UpdateResourceA, BeginUpdateResourceA, EndUpdateResourceA). It may also have some user interface interaction through WinExec and GetMessageA. The low entropy in the BSS section suggests minimal dynamic data allocation at runtime, while the high entropy in the .reloc section indicates complex relocation logic. Overall, the program's behavior suggests a potentially versatile executable with file, process, registry, network, and resource management capabilities.

======================================================================
[4] TRUE CATEGORY: informationstealer
    imports: ['kernel32.dll', 'user32.dll', 'advapi32.dll', 'oleaut32.dll', 'version.dll', 'gdi32.dll', 'ole32.dll', 'comctl32.dll']
    sections: ['CODE', 'DATA', 'BSS', '.idata', '.tls', '.rdata', '.reloc', '.rsrc', '/92']
----------------------------------------------------------------------
The program appears to be a graphical user interface (GUI) application with window management capabilities, potentially incorporating image lists for visual elements. It can interact with system parameters, windows, menus, cursors, and dialog boxes. It may also handle file version information and system metrics. Network activity is not suggested by the provided features, nor are any indications of file manipulation, persistence, or evasion/packing techniques. The entropy values suggest a relatively organized structure for the code and data sections, which is typical for GUI applications.

======================================================================
[5] TRUE CATEGORY: informationstealer
    imports: ['mscoree.dll']
    sections: ['.text', '.rsrc', '.reloc']
----------------------------------------------------------------------
The program appears to be a Windows executable (PE file) designed for execution on a .NET environment. The primary function (_CorExeMain) is imported from mscoree.dll, suggesting it's a managed application that follows the Common Language Runtime (CLR) execution model. The low entropy in the resource section (.rsrc) and relocation section (.reloc) indicates minimal use of resources and dynamic memory allocation, while the higher entropy in the code section (.text) suggests complex logic execution. This program is likely to execute .NET code upon launch but offers limited insights into specific behaviors such as file operations, network activity, or evasion techniques due to the sparse features provided.

======================================================================
[6] TRUE CATEGORY: ransomware
    imports: ['KERNEL32.dll', 'USER32.dll', 'ole32.dll']
    sections: ['.text', '.rdata', '.data', '.rsrc', '.reloc']
----------------------------------------------------------------------
The program appears to be capable of file operations (ReadFile, WriteFile, CreateFileA), process manipulation (GetCurrentProcess, TerminateProcess, SetUnhandledExceptionFilter, IsDebuggerPresent), memory management (VirtualProtect, LocalAlloc, HeapFree, HeapAlloc, VirtualAlloc, HeapReAlloc), and some degree of interaction with the Windows API (GetLastError, FindActCtxSectionStringW, SetVolumeMountPointW). It also includes functions for handling critical sections (InitializeCriticalSection, DeleteCriticalSection, EnterCriticalSection, LeaveCriticalSection) and exceptions (RtlUnwind, RaiseException), suggesting potential for thread synchronization and error handling. The program may also interact with the console (WriteConsoleA, WriteConsoleW, GetConsoleCP, GetConsoleOutputCP), and could potentially utilize network resources via USER32.dll's DdeClientTransaction function, although this is less certain based on the provided evidence.

======================================================================
[7] TRUE CATEGORY: worm
    imports: ['KERNEL32.DLL', 'ADVAPI32.dll', 'MSVCRT.dll', 'USER32.dll', 'WS2_32.dll']
    sections: ['UPX0', 'UPX1', '.rsrc']
----------------------------------------------------------------------
The program appears to be a compacted executable (UPX) with three sections, suggesting minimal code obfuscation. It interacts with various Windows APIs for process management (ExitProcess), registry manipulation (RegCloseKey), time functions (time from MSVCRT.dll), and string formatting (wsprintfA from USER32.dll). The presence of WS2_32.dll suggests potential network capabilities, although no specific network functions are imported, leaving the nature of this interaction unclear. Limited indicators suggest process or memory manipulation and possibly file operations, but further analysis is needed for definitive conclusions.

======================================================================
[8] TRUE CATEGORY: dropper
    imports: ['KERNEL32.dll', 'USER32.dll', 'ADVAPI32.dll']
    sections: ['.text', '.rdata', '.data', '.rsrc', '.luczwh']
----------------------------------------------------------------------
The program appears to be a Windows executable with file and registry operations capabilities. It can interact with the file system using functions like FindFirstFileA, CreateFileA, ReadFile, WriteFile, VirtualAlloc, VirtualFree, and TerminateProcess. It also has the ability to manipulate memory with VirtualAlloc, VirtualFree, HeapFree, HeapAlloc, HeapReAlloc, and HeapDestroy. The program can access system information using GetVersion, GetCurrentProcess, GetLastError, GetModuleHandleA, GetCommandLineA, and GetEnvironmentStrings. It can create directories with CreateDirectoryA and modify the registry with RegOpenKeyA and RegSetValueExA. Additionally, it can interact with user interfaces through MessageBoxA, and network activity is suggested by WideCharToMultiByte and MultiByteToWideChar functions. However, the indicators are limited due to sparse features provided.

======================================================================
[9] TRUE CATEGORY: virus
    imports: ['MSVBVM60.DLL']
    sections: ['.text', '.data', '.rsrc']
----------------------------------------------------------------------
The program appears to be an application using Microsoft Visual Basic for Applications (VBA) macros, as indicated by the imports from MSVBVM60.DLL. This includes functions for data manipulation, string handling, error management, and object creation/destruction. The .text section with high entropy suggests complex execution logic, while the .rsrc section's entropy indicates resource data such as images or icons. However, limited evidence suggests no clear indicators of file operations, network activity, persistence, process or memory manipulation, or evasion/packing techniques.

======================================================================
[10] TRUE CATEGORY: worm
    imports: ['ADVAPI32.dll', 'SHELL32.dll', 'MPR.dll', 'KERNEL32.dll', 'USER32.dll', 'WS2_32.dll']
    sections: ['.text', '.rdata', '.data']
----------------------------------------------------------------------
The program appears to be capable of executing system services, manipulating processes, and interacting with network resources. It can open, close, and modify keys in the registry, start and terminate processes, enumerate and control services, connect and disconnect from network resources, and find and execute files on the local system. Additionally, it has capabilities for memory management, thread creation, and time manipulation. The program may also have some degree of persistence due to its ability to interact with startup settings and create files. However, the indicators are limited as no functions related to evasion or packing were observed in the given features.

======================================================================
[11] TRUE CATEGORY: trojan
    imports: ['ADVAPI32.dll', 'CRYPT32.dll', 'IPHLPAPI.DLL', 'KERNEL32.DLL', 'msvcrt.dll', 'PSAPI.DLL', 'USER32.dll', 'USERENV.dll', 'WS2_32.dll']
    sections: ['UPX0', 'UPX1', 'UPX2']
----------------------------------------------------------------------
The program appears to be capable of network activity (bind function from WS2_32.dll), process information gathering (GetProcessMemoryInfo from PSAPI.DLL), and user profile management (GetUserProfileDirectoryW from USERENV.dll). It also has functions for loading libraries dynamically (LoadLibraryA from KERNEL32.DLL) and protecting memory (VirtualProtect from KERNEL32.DLL), suggesting potential process or memory manipulation. The low entropy of the UPX0 section indicates possible compression or packing, while the higher entropy of UPX1 and UPX2 sections may suggest uncompressed code or data. Limited file operations are suggested by the atof function from msvcrt.dll for floating-point conversion. No clear evidence of evasion techniques is present in the given features.

======================================================================
[12] TRUE CATEGORY: downloader
    imports: ['WININET.dll', 'KERNEL32.dll', 'USER32.dll', 'SHELL32.dll']
    sections: ['.text', '.rdata', '.reloc']
----------------------------------------------------------------------
This Windows PE program appears to be capable of network activity, file operations, and process manipulation. The imports from WININET.dll suggest it can establish connections (InternetConnectW), send requests (HttpSendRequestW), read responses (InternetReadFile), and query information about the connection (HttpQueryInfoW). KERNEL32.dll imports indicate file operations such as creating, reading, writing, and deleting files (CreateFileW, ReadFile, WriteFile, DeleteFileW), as well as obtaining file size and current directory (GetFileSize, GetCurrentDirectoryW). The program can also manipulate memory (HeapCreate, HeapAlloc) and execute other processes (ShellExecuteW). Limited evidence suggests potential for persistence through the use of temporary files (GetTempPathW). However, the indicators are sparse, providing only a general idea of its capabilities.

======================================================================
[13] TRUE CATEGORY: trojan
    imports: ['KERNEL32.dll', 'USER32.dll', 'comdlg32.dll', 'ADVAPI32.dll', 'ole32.dll', 'MFC42.DLL', 'MSVCRT.dll', 'MSVCP60.dll']
    sections: ['.text', '.rdata', '.data', '.rsrc']
----------------------------------------------------------------------
The program appears to be a custom executable with Windows GUI capabilities (MessageBoxA, GetFileTitleA from USER32.dll), file manipulation functions (CopyFileA, CreateFileA, WriteFile), process creation (CreateProcessA), and some degree of interaction with the registry (RegOpenKeyExA, RegQueryValueExA, RegCreateKeyA, RegDeleteValueA, RegSetValueExA, RegCloseKey). It also includes libraries related to memory management (MFC42.DLL, MSVCRT.dll, MSVCP60.dll), suggesting it may manipulate the memory of other processes or allocate its own. However, the evidence is limited and does not definitively indicate network activity, persistence mechanisms, or evasion techniques.

======================================================================
[14] TRUE CATEGORY: downloader
    imports: ['KERNEL32.dll', 'USER32.dll', 'ADVAPI32.dll', 'SHLWAPI.dll']
    sections: ['.text', '.rdata', '.data', '.rsrc']
----------------------------------------------------------------------
The program appears to be capable of file manipulation (CreateFileA, CopyFileA, MoveFileA, DeleteFileA), process management (TerminateProcess, GetModuleHandleA, CreateProcess), memory allocation and protection (VirtualAllocEx, VirtualProtect, HeapAlloc, HeapFree), network activity (GetLongPathNameA, ExpandEnvironmentStringsA), cryptographic operations (CryptGenRandom, CryptAcquireContextA, CloseServiceHandle), and logging (OutputDebugStringA). It may also interact with the user through message boxes (MessageBoxA) and perform string manipulations (lstrcpyA, lstrcatA, lstrlenA, lstrcmpiA, wsprintfA, StrChrA). The program's behavior suggests it could potentially execute commands or scripts (WinExec), but this is not definitively supported by the provided features.

======================================================================
[15] TRUE CATEGORY: backdoor
    imports: ['ole32.DLL', 'OLEAUT32.DLL', 'WININET.DLL', 'KERNEL32.DLL', 'USER32.DLL', 'GDI32.DLL', 'ADVAPI32.DLL', 'CRTDLL.DLL']
    sections: ['.text', '.bss', '.data', '.idata', '.aajaic']
----------------------------------------------------------------------
The program appears to be a custom Windows application with various capabilities. It interacts heavily with the operating system (kernel32, user32, gdi32, advapi32), suggesting it manages windows, graphics, and system-level operations. Network activity is suggested by the use of wininet functions for URL cache manipulation. File operations are indicated by CreateFileA, CopyFileA, DeleteFileA imports. It also has capabilities for process management (CreateProcessA, TerminateProcess), thread creation (CreateThread), and memory manipulation (LocalAlloc, LocalFree). Persistence mechanisms are not evident from the provided features. Evasion or packing techniques are not suggested by the given data.

======================================================================
[16] TRUE CATEGORY: dropper
    imports: ['KERNEL32.DLL', 'MSVCRT.dll', 'SHLWAPI.dll', 'USER32.dll']
    sections: ['UPX0', 'UPX1', 'UPX2']
----------------------------------------------------------------------
The program appears to be a compacted executable (UPX) with three sections, suggesting it may compress or decompress files for smaller size or stealth purposes. It interacts with various system libraries such as KERNEL32, USER32, MSVCRT, and SHLWAPI, indicating potential capabilities in process management, string manipulation, file existence checks, and possibly user interface interactions. The program may load libraries dynamically (LoadLibraryA), modify memory (VirtualProtect, VirtualAlloc, VirtualFree), and exit the system (ExitProcess). However, limited indicators prevent definitive conclusions about file operations, network activity, persistence, or evasion techniques.

======================================================================
[17] TRUE CATEGORY: informationstealer
    imports: ['kernel32.dll', 'user32.dll', 'advapi32.dll', 'oleaut32.dll', 'version.dll', 'gdi32.dll', 'ole32.dll', 'comctl32.dll']
    sections: ['CODE', 'DATA', 'BSS', '.idata', '.tls', '.rdata', '.reloc', '.rsrc', '/92']
----------------------------------------------------------------------
The program appears to be a graphical user interface (GUI) application with window management capabilities, potentially incorporating image lists for visual elements. It can interact with system parameters, windows, menus, cursors, and dialog boxes. It may also handle file version information and system metrics. Network activity is not suggested by the provided features, nor are any indications of file manipulation, persistence, or evasion/packing techniques. The entropy values suggest a relatively organized structure for the code and data sections, which is typical for GUI applications.

======================================================================
[18] TRUE CATEGORY: downloader
    imports: ['user32.dll', 'GDI32.dll', 'Winmm.dll', 'Msacm32.dll', 'IMM32.dll', 'kernel32.dll', 'OLE32.dll']
    sections: ['.buildi', '.show', 'M7/nWLy', '/42', '.po4', '.data2', '/30', '/4', 'new_imp', '.po5', '.lzmjSu', 'usj', '.opc', 'gfelmge', 'PAGEKDD', 'new_imp', 'ordo', '\\\\\\\\xb8', 'new_imp', 'M7/nWLy', 'new_imp', 'new_imp', '.bin', 'PAGEKDD']
----------------------------------------------------------------------
The program appears to be a graphical user interface (GUI) application with custom drawing capabilities. It interacts with the Windows operating system for window management, menu creation, and input handling. It also utilizes text rendering functions and can potentially manipulate the clipboard. Additionally, it has support for loading bitmaps and fonts, suggesting graphic-intensive features. The program may not exhibit significant file or network operations, process manipulation, or evasion/packing techniques based on the provided evidence. However, the presence of certain libraries like OLE32 and kernel32 suggests potential for dynamic behavior beyond static analysis.

======================================================================
[19] TRUE CATEGORY: ransomware
    imports: ['KERNEL32.dll', 'USER32.dll']
    sections: ['.text', '.rdata', '.data', '.reloc']
----------------------------------------------------------------------

In [31]:
row = features_df.iloc[1]   # sample 2 (the ransomware, KERNEL32 + USER32 only)

print("TRUE CATEGORY:", row["category"])
print()
print("FULL FEATURE RECORD (all functions):")
for dll, funcs in row["imports"].items():
    print(f"\n{dll}:")
    print(f"  {funcs}")
print()
print("=" * 60)
print("DESCRIPTION:")
print(row["description"])

TRUE CATEGORY: ransomware

FULL FEATURE RECORD (all functions):

KERNEL32.dll:
  ['GetConsoleOutputCP', 'DeviceIoControl', 'VirtualAlloc', 'GetTempPathW', 'GetLastError', 'FileTimeToSystemTime', 'SetFileShortNameA', 'FindAtomA', 'GetProcAddress', 'CreateMailslotW', 'GetTickCount', 'HeapSize', 'WriteConsoleW', 'SetFilePointerEx', 'LoadLibraryW', 'GetSystemTimeAdjustment', 'SetStdHandle', 'WideCharToMultiByte', 'EnterCriticalSection', 'LeaveCriticalSection', 'DeleteCriticalSection', 'EncodePointer', 'DecodePointer', 'MultiByteToWideChar', 'SetLastError', 'InitializeCriticalSectionAndSpinCount', 'CreateEventW', 'TlsAlloc', 'TlsGetValue', 'TlsSetValue', 'TlsFree', 'GetSystemTimeAsFileTime', 'GetModuleHandleW', 'LCMapStringW', 'GetLocaleInfoW', 'GetStringTypeW', 'GetCPInfo', 'CloseHandle', 'SetEvent', 'ResetEvent', 'WaitForSingleObjectEx', 'UnhandledExceptionFilter', 'SetUnhandledExceptionFilter', 'GetCurrentProcess', 'TerminateProcess', 'IsProcessorFeaturePresent', 'IsDebuggerPresent', 'GetStartupInfoW', 'QueryPerformanceCounter', 'GetCurrentProcessId', 'GetCurrentThreadId', 'InitializeSListHead', 'RtlUnwind', 'RaiseException', 'FreeLibrary', 'LoadLibraryExW', 'ExitProcess', 'GetModuleHandleExW', 'HeapAlloc', 'HeapReAlloc', 'HeapFree', 'GetModuleFileNameA', 'GetStdHandle', 'WriteFile', 'GetACP', 'IsValidLocale', 'GetUserDefaultLCID', 'EnumSystemLocalesW', 'FlushFileBuffers', 'GetConsoleCP', 'GetConsoleMode', 'GetFileType', 'GetProcessHeap', 'FindClose', 'FindFirstFileExA', 'FindNextFileA', 'IsValidCodePage', 'GetOEMCP', 'GetCommandLineA', 'GetCommandLineW', 'GetEnvironmentStringsW', 'FreeEnvironmentStringsW', 'CreateFileW']

USER32.dll:
  ['SetPropA', 'GetMenuStringW']

============================================================
DESCRIPTION:
The program appears to be capable of process manipulation, file I/O operations, and some degree of interaction with the user interface. It utilizes functions for creating, allocating, and managing memory (VirtualAlloc, HeapSize, HeapAlloc, HeapReAlloc, HeapFree), handling files (CreateFileW, WriteFile, FindFirstFileExA, FindNextFileA), interacting with the console (GetConsoleOutputCP, WriteConsoleW), and manipulating processes (TerminateProcess, GetCurrentProcess). Additionally, it can access system information (GetSystemTimeAdjustment, GetLocaleInfoW, GetStringTypeW, GetCPInfo) and create events (CreateEventW). The program may also have some level of network activity through the use of CreateMailslotW, but this is not definitive. The entropy values suggest a mix of executable code and data sections, with no clear indicators of packing or evasion techniques.

In [32]:
import re

def check_grounding(record, description):
    all_functions = set()
    for funcs in record["imports"].values():
        for f in funcs:
            all_functions.add(f.lower())

    mentioned = re.findall(r'\b[A-Z][A-Za-z0-9]+[A-Z][A-Za-z0-9]*\b', description)

    supported = []
    unsupported = []
    for token in mentioned:
        if token.lower() in all_functions:
            supported.append(token)
        else:
            unsupported.append(token)

    return supported, unsupported


total_mentioned = 0
total_supported = 0
flagged = []

for i, row in features_df.iterrows():
    supported, unsupported = check_grounding(row.to_dict(), row["description"])
    total_mentioned += len(supported) + len(unsupported)
    total_supported += len(supported)
    if unsupported:
        flagged.append((i + 1, row["category"], unsupported))

print(f"function-like mentions checked: {total_mentioned}")
print(f"supported by the feature record: {total_supported}")
print(f"not matched: {total_mentioned - total_supported}")
print()
print("samples with unmatched tokens (need eyeballing):")
for idx, cat, unmatched in flagged:
    print(f"  [{idx}] {cat}: {unmatched}")

function-like mentions checked: 291
supported by the feature record: 234
not matched: 57

samples with unmatched tokens (need eyeballing):
  [1] virus: ['GUI']
  [3] backdoor: ['WSASocket', 'BSS']
  [4] informationstealer: ['GUI', 'GUI']
  [5] informationstealer: ['NET', 'CLR', 'NET']
  [6] ransomware: ['API', 'USER32']
  [7] worm: ['UPX', 'APIs', 'MSVCRT', 'USER32']
  [9] virus: ['VBA', 'MSVBVM60', 'DLL']
  [11] trojan: ['PSAPI', 'DLL', 'USERENV', 'KERNEL32', 'DLL', 'KERNEL32', 'DLL', 'UPX0', 'UPX1', 'UPX2']
  [12] downloader: ['WININET', 'KERNEL32']
  [13] trojan: ['GUI', 'USER32', 'MFC42', 'DLL', 'MSVCRT', 'MSVCP60']
  [14] downloader: ['CreateProcess']
  [15] backdoor: ['URL']
  [16] dropper: ['UPX', 'KERNEL32', 'USER32', 'MSVCRT', 'SHLWAPI']
  [17] informationstealer: ['GUI', 'GUI']
  [18] downloader: ['GUI', 'OLE32']
  [19] ransomware: ['DLLs', 'KERNEL32', 'USER32']
  [20] backdoor: ['API', 'KERNEL32', 'DLL']
  [24] dropper: ['UPX', 'KERNEL32', 'USER32', 'MSVCRT', 'SHLWAPI']

In [33]:
for idx in [2, 13]:   # samples 3 and 14 (zero-indexed)
    row = features_df.iloc[idx]
    print("=" * 60)
    print(f"SAMPLE {idx+1} ({row['category']})")
    print("=" * 60)
    for dll, funcs in row["imports"].items():
        print(f"\n{dll}:")
        print(f"  {funcs}")
    print()
    print("DESCRIPTION:")
    print(row["description"])
    print()

============================================================
SAMPLE 3 (backdoor)
============================================================

kernel32.dll:
  ['WritePrivateProfileStringA', 'WinExec', 'UpdateResourceA', 'Sleep', 'SetFilePointer', 'ReadFile', 'GetSystemDirectoryA', 'GetLastError', 'GetFileAttributesA', 'FindNextFileA', 'FindFirstFileA', 'FindClose', 'FileTimeToLocalFileTime', 'FileTimeToDosDateTime', 'ExitProcess', 'EndUpdateResourceA', 'DeleteFileA', 'CreateThread', 'CreateMutexA', 'CreateFileA', 'CreateDirectoryA', 'CopyFileA', 'CloseHandle', 'BeginUpdateResourceA']

user32.dll:
  ['SetTimer', 'GetMessageA', 'DispatchMessageA', 'CharUpperBuffA']

advapi32.dll:
  ['RegQueryValueExA', 'RegOpenKeyExA', 'RegCloseKey']

oleaut32.dll:
  ['SysFreeString']

wsock32.dll:
  ['WSACleanup', 'WSAStartup', 'gethostbyname', 'socket', 'send', 'select', 'recv', 'ntohs', 'listen', 'inet_ntoa', 'inet_addr', 'htons', 'htonl', 'getsockname', 'connect', 'closesocket', 'bind', 'accept']

DESCRIPTION:
The program appears to be capable of file operations (CreateFileA, CopyFileA, DeleteFileA, CreateDirectoryA), process manipulation (CreateThread, ExitProcess), registry access (RegQueryValueExA, RegOpenKeyExA, RegCloseKey), network activity (WSASocket, send, recv, gethostbyname), and resource management (UpdateResourceA, BeginUpdateResourceA, EndUpdateResourceA). It may also have some user interface interaction through WinExec and GetMessageA. The low entropy in the BSS section suggests minimal dynamic data allocation at runtime, while the high entropy in the .reloc section indicates complex relocation logic. Overall, the program's behavior suggests a potentially versatile executable with file, process, registry, network, and resource management capabilities.

============================================================
SAMPLE 14 (downloader)
============================================================

KERNEL32.dll:
  ['ExitProcess', 'ReadFile', 'HeapAlloc', 'GetProcessHeap', 'GetFileSize', 'CopyFileA', 'GetModuleFileNameA', 'LeaveCriticalSection', 'GetProcAddress', 'EnterCriticalSection', 'VirtualProtect', 'InitializeCriticalSection', 'GetModuleHandleA', 'LockResource', 'LoadResource', 'SetFilePointer', 'FindResourceA', 'GetLastError', 'MoveFileA', 'DeleteFileA', 'lstrcmpiA', 'GetLongPathNameA', 'ExpandEnvironmentStringsA', 'GetTickCount', 'OutputDebugStringA', 'lstrlenA', 'TerminateProcess', 'VirtualAllocEx', 'HeapFree', 'VirtualAlloc', 'Sleep', 'lstrcpyA', 'lstrcatA', 'CreateFileA', 'WriteFile', 'CloseHandle', 'SizeofResource', 'WinExec']

USER32.dll:
  ['wsprintfA', 'MessageBoxA']

ADVAPI32.dll:
  ['CloseServiceHandle', 'CryptGenRandom', 'CryptReleaseContext', 'EnumServicesStatusA', 'OpenSCManagerA', 'CryptAcquireContextA']

SHLWAPI.dll:
  ['PathRemoveFileSpecA', 'StrChrA']

DESCRIPTION:
The program appears to be capable of file manipulation (CreateFileA, CopyFileA, MoveFileA, DeleteFileA), process management (TerminateProcess, GetModuleHandleA, CreateProcess), memory allocation and protection (VirtualAllocEx, VirtualProtect, HeapAlloc, HeapFree), network activity (GetLongPathNameA, ExpandEnvironmentStringsA), cryptographic operations (CryptGenRandom, CryptAcquireContextA, CloseServiceHandle), and logging (OutputDebugStringA). It may also interact with the user through message boxes (MessageBoxA) and perform string manipulations (lstrcpyA, lstrcatA, lstrlenA, lstrcmpiA, wsprintfA, StrChrA). The program's behavior suggests it could potentially execute commands or scripts (WinExec), but this is not definitively supported by the provided features.